service: kanban

plugins:
 - serverless-offline

provider:
 name: aws
 runtime: nodejs20.x

functions:
 main:
   handler: dist/src/serverless.handler
   events:
     - http: 
         method: ANY
         path: /
     - http:
         method: any
         path: /{proxy+}